# Generated by Django 5.2.10 on 2026-02-05 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chai_image/')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('chai_type', models.CharField(choices=[('ML', 'Masala'), ('MK', 'Milk'), ('EL', 'Elaichi'), ('GR', 'Ginger'), ('PL', 'Plain')], max_length=2)),
            ],
        ),
    ]
